# Generated by Django 4.1.9 on 2023-06-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100, null=True)),
                ('images', models.ImageField(upload_to='')),
            ],
        ),
    ]
